package com.mpp.disaster.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CenterTypeWrapperAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterTypeWrapperAllPropertiesEquals(CenterTypeWrapper expected, CenterTypeWrapper actual) {
        assertCenterTypeWrapperAutoGeneratedPropertiesEquals(expected, actual);
        assertCenterTypeWrapperAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterTypeWrapperAllUpdatablePropertiesEquals(CenterTypeWrapper expected, CenterTypeWrapper actual) {
        assertCenterTypeWrapperUpdatableFieldsEquals(expected, actual);
        assertCenterTypeWrapperUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterTypeWrapperAutoGeneratedPropertiesEquals(CenterTypeWrapper expected, CenterTypeWrapper actual) {
        assertThat(actual)
            .as("Verify CenterTypeWrapper auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterTypeWrapperUpdatableFieldsEquals(CenterTypeWrapper expected, CenterTypeWrapper actual) {
        assertThat(actual)
            .as("Verify CenterTypeWrapper relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterTypeWrapperUpdatableRelationshipsEquals(CenterTypeWrapper expected, CenterTypeWrapper actual) {
        assertThat(actual)
            .as("Verify CenterTypeWrapper relationships")
            .satisfies(a -> assertThat(a.getCenter()).as("check center").isEqualTo(expected.getCenter()));
    }
}
