package com.mpp.disaster.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OfficialMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialMessageAllPropertiesEquals(OfficialMessage expected, OfficialMessage actual) {
        assertOfficialMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertOfficialMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialMessageAllUpdatablePropertiesEquals(OfficialMessage expected, OfficialMessage actual) {
        assertOfficialMessageUpdatableFieldsEquals(expected, actual);
        assertOfficialMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialMessageAutoGeneratedPropertiesEquals(OfficialMessage expected, OfficialMessage actual) {
        assertThat(actual)
            .as("Verify OfficialMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialMessageUpdatableFieldsEquals(OfficialMessage expected, OfficialMessage actual) {
        assertThat(actual)
            .as("Verify OfficialMessage relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getTimePosted()).as("check timePosted").isEqualTo(expected.getTimePosted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfficialMessageUpdatableRelationshipsEquals(OfficialMessage expected, OfficialMessage actual) {
        // empty method
    }
}
